/**
 * Centralized error code constants.
 * All API error responses should reference these codes for consistency.
 */
export const ErrorCodes = {
  // Auth
  MISSING_AUTH: 'MISSING_AUTH',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_REFRESH: 'INVALID_REFRESH',
  REFRESH_REVOKED: 'REFRESH_REVOKED',
  REFRESH_MISMATCH: 'REFRESH_MISMATCH',
  REFRESH_ALREADY_USED: 'REFRESH_ALREADY_USED',
  INVALID_CODE: 'INVALID_CODE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  DEV_AUTH_LOCAL_ONLY: 'DEV_AUTH_LOCAL_ONLY',
  AUTH_NOT_CONFIGURED: 'AUTH_NOT_CONFIGURED',
  INVALID_ROLE: 'INVALID_ROLE',

  // Authorization
  STUDENT_ONLY: 'STUDENT_ONLY',
  TEACHER_ONLY: 'TEACHER_ONLY',
  ENTRY_ACCESS_DENIED: 'ENTRY_ACCESS_DENIED',
  COURSE_ACCESS_DENIED: 'COURSE_ACCESS_DENIED',
  TEACHER_REQUIRED: 'TEACHER_REQUIRED',

  // Resources
  NOT_FOUND: 'NOT_FOUND',
  ENTRY_NOT_FOUND: 'ENTRY_NOT_FOUND',
  ARTIFACT_NOT_FOUND: 'ARTIFACT_NOT_FOUND',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  ENTRY_DELETED: 'ENTRY_DELETED',

  // State
  ENTRY_LOCKED: 'ENTRY_LOCKED',
  ENTRY_NOT_SUBMITTED: 'ENTRY_NOT_SUBMITTED',
  ARTIFACTS_NOT_UPLOADED: 'ARTIFACTS_NOT_UPLOADED',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  UPLOAD_INVALID: 'UPLOAD_INVALID',
  MISSING_STORAGE_KEY: 'MISSING_STORAGE_KEY',
  INVALID_TARGET: 'INVALID_TARGET',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ID_CONFLICT: 'ID_CONFLICT',

  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;
